const express = require('express');
const dotenv = require('dotenv');
const helmet = require('helmet');
const cors = require('cors');
const morgan = require('morgan');
const port = process.env.PORT || 4000;
const connectDB = require('./config/connectDB');
const routes = require('./routes');
dotenv.config();
const app = express();
app.use(express.json({extended: true, limit: '50mb'}));
app.use(express.urlencoded({ extended: true, limit: '50mb'}));
app.use(cors());
app.use(helmet());
app.use(morgan("dev"));
(async() =>{
    await connectDB();
})();
routes(app);
app.listen(port, () => console.log(`Server listening on port http://localhost:${port}`));